apiVersion: v1
kind: Namespace
metadata:
  name: c2c-azure-thulasi-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-azure-thulasi-deployment
  namespace: c2c-azure-thulasi-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: eslattacr.azurecr.io/azure-demo-push-repo:b2ffcaa3d0946b99354059c333931dba489a0123

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-azure-thulasi-label
  name: c2c-azure-thulasi-service
  namespace: c2c-azure-thulasi-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---